### ISSUE TITLE
add services button login, and remove unused buttons in the service panel

### ISSUE THREAD

**Issue by criloz** [nebtex/menshend-ui#11]
![captura realizada el 2017-04-25 01 23 06](https://cloud.githubusercontent.com/assets/1408540/25371439/64d84c5e-2956-11e7-8eea-7f2ff172ecdc.png)
![captura realizada el 2017-04-25 01 25 22](https://cloud.githubusercontent.com/assets/1408540/25371441/6792ce9c-2956-11e7-8a6a-51945766b95b.png)

**Comment by Ignusmart** [comment]
@criloz done
